stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building the WACC compiler..."
    - make

test-job:
  stage: test
  script:
    - echo "Testing scanner/parser on all WACC file in test/..."
    - make 
    - for file in src/test/*.wacc; do echo $(./grun antlr.Full program -tree < $file) ; done

test-job2:
  stage: test
  script:
    - echo "Testing <function 2> of the WACC compiler..."
    - echo "unimplemented"
