stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building the web app..."
    - make

test-job:
  stage: test
  script:
    - echo "Testing the web app..."
    - echo "unimplemented"