stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building the WACC compiler..."
    - make

test-lexer-parser:
  stage: test
  script:
    - echo "Testing scanner/parser on all WACC file in test/..."
    - ./grun antlr.WACC program -tree $(find ./src/test/examples -name "*.wacc") 2> ./log/parser_error.log

test-semantics:
  stage: test
  script:
    - echo "Testing <function 2> of the WACC compiler..."
    - echo "unimplemented"
